apiVersion: 1

datasources:
    - name: senseops
      type: influxdb
      access: proxy
      url: http://influxdb-v1:8086
      database: senseops
      user: goran
      secureJsonData:
          password: mysecret
      jsonData:
          httpMode: GET
      uid: bf7gj7evi44xsd
