apiVersion: 1

datasources:
    - name: Butler SOS
      type: influxdb
      access: proxy
      url: http://influxdb:8086
      database: butler-sos
      jsonData:
          httpMode: GET
          httpHeaderName1: Authorization
      secureJsonData:
          httpHeaderValue1: Token butlersos-token
      uid: bf7gj7evi44xsd
